### PR TITLE
Add support for multiboot2.

### LINKED ISSUE #30: Adapt to multiboot2 v2.0
About a year ago a new version of the multiboot2 specification was created. It is backwards compatible to v1.6 which is currently used in this repository. The new version provides features useful for EFI based systems. For example among others a copy of the ACPI RSDP structure is available in the boot information.

Necessary changes to this crate would be adding the necessary API to access the new tags in the multiboot2 boot information and adapt to all other differences between the two versions of the specification.

The specification is available (seemingly since ever) in the GRUB git repository https://git.savannah.gnu.org/git/grub.git on the `multiboot2` branch.
In it, the following commands have to be executed: `./autogen.sh; ./configure; make pdf`. This will generate a pdf file `doc/multiboot.pdf` which contains the multiboot2 specification.
I don't know exactly what dependencies are required to generate this file, but among them are certainly `gnulib` for `autogen.sh` and `texinfo` because the spec is written in texinfo format.

If you don't want to go through the generation process and trust me (that I didn't mess with the file), you can download the file attached below. I don't guarantee that the information in the file I have uploaded is correct. (If in doubt, generate the file yourself.) I built it off commit `d81931d0e5830467b778f20b7eca761240d337f7` made on 2017-03-10.
[multiboot.pdf](https://github.com/phil-opp/multiboot2-elf64/files/1185888/multiboot.pdf)

P.S.: I just read the discussion about issue #22. If this repo is copied and/or redone, it would still be great to provide support for the newer multiboot2 features. If this repo isn't forked, my idea still stands.

### PR DESCRIPTION
**Pull request by Caduser2020**
Fix #30 
[Multiboot 2.0](https://www.gnu.org/software/grub/manual/multiboot2/multiboot.html)

TODO:

- [x] Testing
- [x] More EFI tables: SDT, image handle.

### CODE REVIEW

**Comment by Caduser2020** [comment]
@rust-osdev/multiboot2 Ready for review! May I be added to the organization? I would like to help clear up some issues as I plan to use this crate in some embedded apps.

**Comment by phil-opp** [comment]
@Caduser2020 I sent you an invite to the organization! I'm no longer a member of the @rust-osdev/multiboot2 team, though, so I'll leave the review to others.

**Comment by IsaacWoods** [comment]
Travis isn't reporting the status for some reason, but I've checked and this PR passes CI. Code looks fine to me too, thanks for the contribution!

@Caduser2020 - I can add you to our multiboot2 team once you've accepted the invitation to the organisation. Ping me here or on Gitter when you've done so :)

**Comment by Caduser2020** [comment]
@IsaacWoods Thanks!

**Pull request merged**
