### PR TITLE
Fix elf sections so it returns the last section.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by robert-w-gries** [comment]
Can you add a testcase that explicitly tests the number of elf sections?  Maybe re-use the input data from the grub test, so we don't blow up the size of src/lib.rs.

**Comment by ahmedcharles** [comment]
Added a new test focused on elf sections. It only has one section, so the bug is painfully obvious.

**Comment by xacrimon** [comment]
Have you tested? Short on time and can't test myself.

**Comment by xacrimon** [comment]
@ahmedcharles

**Comment by ahmedcharles** [comment]
Yeah, I wouldn't add a test without running it. Also, CI passed.

**Comment by ahmedcharles** [comment]
I've also tested it in a kernel.

**Comment by robert-w-gries** [comment]
@xacrimon Do you have permissions for merging?  If so, you can probably go ahead and merge the reviewed PRs

**Comment by ahmedcharles** [comment]
Thanks.

**Pull request merged**
